#undef Alignment
#undef ColorIntensity
#undef ColorOp
#undef Coord
#undef EventType
#undef EventButton
#undef GlyphBreakType
#undef GlyphIndex
#undef IntCoord
#undef Action
#undef Adjustable
#undef Adjuster
#undef Aggregate
#undef AggregateInfo_List
#undef Align
#undef Allocation
#undef Allotment
#undef ApplicationWindow
#undef ArrayCompositor
#undef BMargin
#undef Background
#undef Banner
#undef Bevel
#undef Bitmap
#undef BitmapRep
#undef Border
#undef BorderFrame
#undef Box
#undef BoxAllocation_List
#undef BoxCanonical
#undef BoxComponent_List
#undef BoxElement
#undef Break
#undef Break_List
#undef Brush
#undef BrushImpl
#undef BrushRep
#undef Button
#undef ButtonList
#undef ButtonState
#undef Canvas
#undef CanvasDamage
#undef CanvasRep
#undef Center
#undef Character
#undef CheckBox
#undef ChoiceItem
#undef ClippingStack
#undef Color
#undef ColorImpl
#undef ColorRep
#undef ColorTable
#undef CompletionEditor
#undef Composition
#undef CompositionComponent_List
#undef Compositor
#undef Control
#undef ControlState
#undef Cursor
#undef CursorRep
#undef DamageList
#undef Deck
#undef Dialog
#undef Discretionary
#undef Display
#undef DisplayRep
#undef DownMover
#undef Enlarger
#undef Event
#undef EventRep
#undef Extension
#undef FileBrowser
#undef FileChooser
#undef FixedSpan
#undef Font
#undef FontFamily
#undef FontFamilyRep
#undef FontImpl
#undef FontRep
#undef Frame
#undef Glue
#undef Glyph
#undef GrabList
#undef Group
#undef GrowingBSpline
#undef GrowingClosedBSpline
#undef GrowingMultiLine
#undef GrowingPolygon
#undef GrowingVertices
#undef HBorder
#undef HBox
#undef HCenter
#undef HGlue
#undef HMargin
#undef HRule
#undef HScrollBar
#undef HScroller
#undef HStrut
#undef Handler
#undef Hit
#undef HitImpl
#undef IconWindow
#undef Image
#undef Interactor
#undef InteractorWindow
#undef Kit
#undef KnownFonts
#undef LMargin
#undef LRBox
#undef LRComposition
#undef LRMarker
#undef Label
#undef Layout
#undef LeftMover
#undef Listener
#undef MFKit
#undef MFKitImpl
#undef Macro
#undef ManagedWindow
#undef ManagedWindowHintInfo
#undef ManagedWindowRep
#undef Margin
#undef MarginFrame
#undef MatchEditor
#undef Menu
#undef MenuBar
#undef MenuItem
#undef MenuItemList
#undef Message
#undef MonoGlyph
#undef MonoKit
#undef MonoKitImpl
#undef MonoScene
#undef Mover
#undef MoverAction
#undef MoverActionBackward
#undef MoverActionForward
#undef OLKit
#undef OLKitImpl
#undef OL_AbbrevButtonGlyph
#undef OL_AnchorGlyph
#undef OL_ButtonGlyph
#undef OL_CheckBoxGlyph
#undef OL_ChiseledBorder
#undef OL_ChoiceItemGlyph
#undef OL_DimpleGlyph
#undef OL_ElevatorGlyph
#undef OL_HorizontalElevatorGlyph
#undef OL_HorizontalMenuMarkGlyph
#undef OL_LRAnchorGlyph
#undef OL_PushPinGlyph
#undef OL_Style
#undef OL_StyleImpl
#undef OL_TBAnchorGlyph
#undef OL_TitleBarGlyph
#undef OL_VerticalElevatorGlyph
#undef OL_VerticalMenuMarkGlyph
#undef Offscreen
#undef OptionDesc
#undef Overlay
#undef PSFont
#undef Page
#undef Painter
#undef PainterRep
#undef Panner
#undef Patch
#undef PathRenderInfo
#undef Pattern
#undef PatternRep
#undef Perspective
#undef PointerHandler
#undef PopupMenu
#undef PopupWindow
#undef Printer
#undef PropertyData
#undef PulldownMenu
#undef PullrightMenu
#undef PushButton
#undef RGBTable
#undef RMargin
#undef RadioButton
#undef Raster
#undef RasterRep
#undef Reducer
#undef Regexp
#undef ReqErr
#undef Requirement
#undef Requisition
#undef Resource
#undef RightMover
#undef RotatingLine
#undef RotatingLineList
#undef RotatingRect
#undef RubberAxis
#undef RubberCircle
#undef RubberClosedSpline
#undef RubberEllipse
#undef RubberGroup
#undef RubberHandles
#undef RubberLine
#undef RubberPointList
#undef RubberRect
#undef RubberSpline
#undef RubberSquare
#undef RubberVertex
#undef Rubberband
#undef Rule
#undef ScalingLine
#undef ScalingLineList
#undef ScalingRect
#undef Scene
#undef ScrollBar
#undef Scroller
#undef Sensor
#undef Session
#undef SessionRep
#undef Shadow
#undef ShadowFrame
#undef Shape
#undef ShapeOf
#undef ShowFrame
#undef SimpleCompositor
#undef Slider
#undef SlidingEllipse
#undef SlidingLine
#undef SlidingLineList
#undef SlidingPointList
#undef SlidingRect
#undef Space
#undef Stencil
#undef StretchingRect
#undef Strut
#undef Style
#undef StyleRep
#undef Subject
#undef Superpose
#undef TBBox
#undef TBComposition
#undef TGlue
#undef TIFFRaster
#undef TMargin
#undef TSolver
#undef Target
#undef TeXCompositor
#undef Telltale
#undef TextBuffer
#undef TextButton
#undef TextDisplay
#undef TextEditor
#undef TextRenderInfo
#undef Tile
#undef TileReversed
#undef TitleFrame
#undef TopLevelWindow
#undef TransformSetter
#undef Transformer
#undef TransformerStack
#undef TransientWindow
#undef Tray
#undef TrayElement
#undef UpMover
#undef VBorder
#undef VBox
#undef VCenter
#undef VGlue
#undef VMargin
#undef VRule
#undef VScrollBar
#undef VScroller
#undef VStrut
#undef Viewport
#undef Window
#undef WindowRep
#undef WindowTable
#undef World
#undef XYMarker
#undef Zoomer
