#undef CopyString
#undef Directory
#undef DirectoryInfo
#undef File
#undef FileInfo
#undef Host
#undef InputFile
#undef List
#undef Math
#undef Memory
#undef NullTerminatedString
#undef OutputFile
#undef StdInput
#undef StdOutput
#undef String
#undef Table
#undef Table2
#undef UniqueString
#undef UniqueStringPool
#undef UniqueStringTable
